# Generated by Django 3.1.3 on 2020-11-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_flowerimage_kittenimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowerimage',
            name='file',
            field=models.ImageField(upload_to='flower/'),
        ),
        migrations.AlterField(
            model_name='kittenimage',
            name='file',
            field=models.ImageField(upload_to='kitten/'),
        ),
    ]
